api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "member-price-discount"
type = "function"
uid = "58f6a1f6-1d1a-c9bb-d0b0-5659f413edf01304d86b"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
